### ISSUE TITLE
G-Buffer Encoder

### ISSUE THREAD

**Issue by jsaisagar** [intel-isl/PhotorealismEnhancement#9]
Hi,

This is an Amazing Work!! Future of gaming is here.
I have a query about about G-Buffer Encoder. 
In the paper it is mentioned "The G-buffer encoder consists of multiple network streams that process the same set of G-buffers."
Does this mean different classes have different networks, one for each class?

Thanks for any help.

**Comment by srrichter** [comment]
Hi,
yes, that is exactly what is meant.
